CREATE TABLE "EMPLOYEES"
 (	"ID" NUMBER(19,0) PRIMARY KEY AUTO_INCREMENT,
	"AGE" NUMBER(10,0),
	"EMAIL_ADDRESS" VARCHAR2(255 BYTE),
	"FIRST_NAME" VARCHAR2(255 BYTE),
	"LAST_NAME" VARCHAR2(255 BYTE)
 );

